apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitty-project
  namespace: webapp  # Ensure the namespace is correct
spec:
  replicas: 2  # Deploy two pods for redundancy and scaling
  selector:
    matchLabels:
      app: kitty-project  # This label matches the service selector
  template:
    metadata:
      labels:
        app: kitty-project  # Labels should match the service selector
    spec:
      containers:
        - name: kitty-project
          image: divyasatpute/kitty:latest  # Make sure this is the correct Docker image
          ports:
            - containerPort: 8501  # Port Streamlit listens on by default
          env:
            - name: ENV_VARIABLE_NAME  # Optional: Add environment variables here if needed
              value: "value"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"  # Define resource requests for better scheduling
            limits:
              memory: "1Gi"
              cpu: "1"  # Define limits to prevent over-consumption of resources
