apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitty-project
  namespace: webapp  # Make sure this matches your service's namespace
spec:
  replicas: 2  # Number of pods to deploy
  selector:
    matchLabels:
      app: kitty-project  # This label should match the service's selector
  template:
    metadata:
      labels:
        app: kitty-project
    spec:
      containers:
        - name: kitty-project
          image: divyasatpute/kitty:latest  # Ensure this is the correct image name
          ports:
            - containerPort: 8080  # Port your app listens on inside the container
          env:
            - name: ENV_VARIABLE_NAME  # Example of environment variable (optional)
              value: "value"
          resources: 
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kitty-project-service
  namespace: webapp
spec:
  selector:
    app: kitty-project  # Ensure this matches the label of the pods created by the deployment
  ports:
    - port: 80        # Port exposed externally
      targetPort: 8080 # Internal port of the container
  type: LoadBalancer   # Creates an external load balancer on cloud providers (e.g., AWS ELB)
