apiVersion: v1
kind: Service
metadata:
  name: kitty-project-service
  labels:
    app: kitty-project
spec:
  selector:
    app: kitty-project
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 8080 # Port on the container
  type: LoadBalancer # Replace with LoadBalancer if you want external access
